data:
  type: image
  train_dir: data/anime-face-full
  test_dir: data/anime-face-full
  img_size: 256
  nlabels: 1
generator:
  name: resnet4
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
discriminator:
  name: resnet4
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: experiments/anime-face-full
  gan_type: standard
  sample_nlabels: 1
  inception_every: 10000
  batch_size: 16
  sample_every: 50
  n_epoch: 100000
test:
  batch_size: 16
  sample_size: 36
  sample_nrow: 6
  compute_inception: true
  conditional_samples: true
interpolations:
#  ys: [15, 157, 307, 321, 442, 483, 484, 525,
#       536, 598, 607, 734, 768, 795, 927, 977,
#       963, 946, 979]
  nzs: 10
  nsubsteps: 75