data:
  type: image
  train_dir:
    task_0: data/continual/task_0
    task_1: data/continual/task_1
    task_2: data/continual/task_2
    task_3: data/continual/task_3
    task_4: data/continual/task_4
    task_5: data/continual/task_5
    task_6: data/continual/task_6
  test_dir: data/continual
  lsun_categories_train: [bedroom_train]
  lsun_categories_test: [bedroom_test]
  img_size: 256
  nlabels: 7
generator:
  name: resnet_mask
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 1
    rank: 5
discriminator:
  name: resnet_mask
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: experiments/cl/dummy
  gan_type: standard
  reg_type: real
  reg_param: 10.
  batch_size: 8
  nworkers: 16
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 200
  sample_nlabels: 30
  inception_every: -1
  save_every: 500
  backup_every: 100000
  restart_every: -1
  mdl_every: 2
  supcon_every: 1000000
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
  model_file: model.pt
  n_epoch: 4
  n_task: 7
  coef_distribution: dirichlet
  mdl_d_wt: 1.0
  mdl_g_wt: 1000.0
test:
  batch_size: 8
  sample_size: 36
  sample_nrow: 6
  use_model_average: true
  compute_inception: false
  conditional_samples: false
  model_file: model.pt
interpolations:
  nzs: 10
  nsubsteps: 75
